- name: Setup Nodes for the cluster
  hosts: all
  become: true
  roles:
    - role: system
# TEMP
#   - role: dev-sec.os-hardening
#      vars:
#        sysctl_overwrite:
#           # Enable IPv4 traffic forwarding.
#           net.ipv4.ip_forward: 1            
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ deploy_user_name }}"
    - role: users